apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"nvidia.com/v1alpha1","kind":"DynamoGraphDeployment","metadata":{"annotations":{},"labels":{"benchmark.nvidia.com/experiment":"exp1-agg-round-robin"},"name":"qwen3-32b-fp8-vllm-agg","namespace":"qwen32-bench"},"spec":{"backendFramework":"vllm","pvcs":[{"create":false,"name":"model-cache"}],"services":{"Frontend":{"componentType":"frontend","envs":[{"name":"HF_HOME","value":"/opt/models"},{"name":"DYN_ROUTER_MODE","value":"round-robin"}],"extraPodSpec":{"mainContainer":{"image":"nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.3.0","workingDir":"/workspace/examples/backends/vllm"}},"replicas":8,"resources":{"limits":{"memory":"128Gi"},"requests":{"cpu":"32","memory":"64Gi"}},"volumeMounts":[{"mountPoint":"/opt/models","name":"model-cache"}]},"VllmWorkerGpu05":{"componentType":"worker","envFromSecret":"hf-token-secret","extraPodSpec":{"dnsPolicy":"ClusterFirst","hostNetwork":false,"mainContainer":{"args":["python3 -m dynamo.vllm \\\n  --model \"$MODEL_PATH\" \\\n  --served-model-name \"$SERVED_MODEL_NAME\" \\\n  --tensor-parallel-size 2 \\\n  --data-parallel-size 1 \\\n  --gpu-memory-utilization 0.90 \\\n  --max-model-len 40960 \\\n  --enable-prefix-caching \\\n  --block-size 128 \\\n  --no-enable-log-requests\n"],"command":["/bin/sh","-c"],"env":[{"name":"SERVED_MODEL_NAME","value":"Qwen/Qwen3-32B-FP8"},{"name":"MODEL_PATH","value":"/opt/models/hub/models--Qwen--Qwen3-32B-FP8/snapshots/aa55da1ecc13d006e8b8e4f54579b1ea8c3db2df"},{"name":"HF_HOME","value":"/opt/models"},{"name":"PYTHONHASHSEED","value":"0"}],"image":"nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.3.0","ports":[{"containerPort":9090,"name":"system"}],"workingDir":"/workspace/examples/backends/vllm"},"nodeSelector":{"kubernetes.io/hostname":"inst-1onle-devrel-rdma-pool"}},"replicas":4,"resources":{"limits":{"gpu":"2"},"requests":{"gpu":"2"}},"sharedMemory":{"size":"40Gi"},"volumeMounts":[{"mountPoint":"/opt/models","name":"model-cache"}]},"VllmWorkerGpu06":{"componentType":"worker","envFromSecret":"hf-token-secret","extraPodSpec":{"dnsPolicy":"ClusterFirst","hostNetwork":false,"mainContainer":{"args":["python3 -m dynamo.vllm \\\n  --model \"$MODEL_PATH\" \\\n  --served-model-name \"$SERVED_MODEL_NAME\" \\\n  --tensor-parallel-size 2 \\\n  --data-parallel-size 1 \\\n  --gpu-memory-utilization 0.90 \\\n  --max-model-len 40960 \\\n  --enable-prefix-caching \\\n  --block-size 128 \\\n  --no-enable-log-requests\n"],"command":["/bin/sh","-c"],"env":[{"name":"SERVED_MODEL_NAME","value":"Qwen/Qwen3-32B-FP8"},{"name":"MODEL_PATH","value":"/opt/models/hub/models--Qwen--Qwen3-32B-FP8/snapshots/aa55da1ecc13d006e8b8e4f54579b1ea8c3db2df"},{"name":"HF_HOME","value":"/opt/models"},{"name":"PYTHONHASHSEED","value":"0"}],"image":"nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.3.0","ports":[{"containerPort":9090,"name":"system"}],"workingDir":"/workspace/examples/backends/vllm"},"nodeSelector":{"kubernetes.io/hostname":"inst-g9dwj-devrel-rdma-pool"}},"replicas":4,"resources":{"limits":{"gpu":"2"},"requests":{"gpu":"2"}},"sharedMemory":{"size":"40Gi"},"volumeMounts":[{"mountPoint":"/opt/models","name":"model-cache"}]}}}}
    nvidia.com/current-worker-hash: 6fa5e7c4
    nvidia.com/current-worker-hash-v2: 6152cbdb
    nvidia.com/dgd-spec: '{"version":1,"spec":{"pvcs":[{"create":false,"name":"model-cache","size":"0"}],"services":{"Frontend":{"resources":{"requests":{"cpu":"32","memory":"64Gi"},"limits":{"memory":"128Gi"}},"envs":[{"name":"HF_HOME","value":"/opt/models"},{"name":"DYN_ROUTER_MODE","value":"round-robin"}],"volumeMounts":[{"name":"model-cache","mountPoint":"/opt/models"}],"extraPodSpec":{"mainContainer":{"name":"","resources":{}}}},"VllmWorkerGpu05":{"resources":{"requests":{"gpu":"2"},"limits":{"gpu":"2"}},"envFromSecret":"hf-token-secret","volumeMounts":[{"name":"model-cache","mountPoint":"/opt/models"}],"extraPodSpec":{"mainContainer":{"name":"","env":[{"name":"SERVED_MODEL_NAME","value":"Qwen/Qwen3-32B-FP8"},{"name":"MODEL_PATH","value":"/opt/models/hub/models--Qwen--Qwen3-32B-FP8/snapshots/aa55da1ecc13d006e8b8e4f54579b1ea8c3db2df"},{"name":"HF_HOME","value":"/opt/models"},{"name":"PYTHONHASHSEED","value":"0"}],"resources":{}}}},"VllmWorkerGpu06":{"resources":{"requests":{"gpu":"2"},"limits":{"gpu":"2"}},"envFromSecret":"hf-token-secret","volumeMounts":[{"name":"model-cache","mountPoint":"/opt/models"}],"extraPodSpec":{"mainContainer":{"name":"","env":[{"name":"SERVED_MODEL_NAME","value":"Qwen/Qwen3-32B-FP8"},{"name":"MODEL_PATH","value":"/opt/models/hub/models--Qwen--Qwen3-32B-FP8/snapshots/aa55da1ecc13d006e8b8e4f54579b1ea8c3db2df"},{"name":"HF_HOME","value":"/opt/models"},{"name":"PYTHONHASHSEED","value":"0"}],"resources":{}}}}}}}'
    nvidia.com/dynamo-operator-origin-version: 1.3.0
  creationTimestamp: "2026-08-12T12:32:06Z"
  finalizers:
  - nvidia.com/finalizer
  generation: 1
  labels:
    benchmark.nvidia.com/experiment: exp1-agg-round-robin
  name: qwen3-32b-fp8-vllm-agg
  namespace: qwen32-bench
  resourceVersion: "926972"
  uid: 0cf36155-9307-49f5-b809-9a8898984eb4
spec:
  backendFramework: vllm
  components:
  - minAvailable: 1
    name: Frontend
    podTemplate:
      spec:
        containers:
        - env:
          - name: HF_HOME
            value: /opt/models
          - name: DYN_ROUTER_MODE
            value: round-robin
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.3.0
          name: main
          resources:
            limits:
              memory: 128Gi
            requests:
              cpu: "32"
              memory: 64Gi
          volumeMounts:
          - mountPath: /opt/models
            name: model-cache
          workingDir: /workspace/examples/backends/vllm
    replicas: 8
    type: frontend
  - minAvailable: 1
    name: VllmWorkerGpu05
    podTemplate:
      spec:
        containers:
        - args:
          - |
            python3 -m dynamo.vllm \
              --model "$MODEL_PATH" \
              --served-model-name "$SERVED_MODEL_NAME" \
              --tensor-parallel-size 2 \
              --data-parallel-size 1 \
              --gpu-memory-utilization 0.90 \
              --max-model-len 40960 \
              --enable-prefix-caching \
              --block-size 128 \
              --no-enable-log-requests
          command:
          - /bin/sh
          - -c
          env:
          - name: SERVED_MODEL_NAME
            value: Qwen/Qwen3-32B-FP8
          - name: MODEL_PATH
            value: /opt/models/hub/models--Qwen--Qwen3-32B-FP8/snapshots/aa55da1ecc13d006e8b8e4f54579b1ea8c3db2df
          - name: HF_HOME
            value: /opt/models
          - name: PYTHONHASHSEED
            value: "0"
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.3.0
          name: main
          ports:
          - containerPort: 9090
            name: system
            protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "2"
            requests:
              nvidia.com/gpu: "2"
          volumeMounts:
          - mountPath: /opt/models
            name: model-cache
          workingDir: /workspace/examples/backends/vllm
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/hostname: inst-1onle-devrel-rdma-pool
    replicas: 4
    sharedMemorySize: 40Gi
    type: worker
  - minAvailable: 1
    name: VllmWorkerGpu06
    podTemplate:
      spec:
        containers:
        - args:
          - |
            python3 -m dynamo.vllm \
              --model "$MODEL_PATH" \
              --served-model-name "$SERVED_MODEL_NAME" \
              --tensor-parallel-size 2 \
              --data-parallel-size 1 \
              --gpu-memory-utilization 0.90 \
              --max-model-len 40960 \
              --enable-prefix-caching \
              --block-size 128 \
              --no-enable-log-requests
          command:
          - /bin/sh
          - -c
          env:
          - name: SERVED_MODEL_NAME
            value: Qwen/Qwen3-32B-FP8
          - name: MODEL_PATH
            value: /opt/models/hub/models--Qwen--Qwen3-32B-FP8/snapshots/aa55da1ecc13d006e8b8e4f54579b1ea8c3db2df
          - name: HF_HOME
            value: /opt/models
          - name: PYTHONHASHSEED
            value: "0"
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.3.0
          name: main
          ports:
          - containerPort: 9090
            name: system
            protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "2"
            requests:
              nvidia.com/gpu: "2"
          volumeMounts:
          - mountPath: /opt/models
            name: model-cache
          workingDir: /workspace/examples/backends/vllm
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/hostname: inst-g9dwj-devrel-rdma-pool
    replicas: 4
    sharedMemorySize: 40Gi
    type: worker
status:
  components:
    Frontend:
      componentKind: PodClique
      componentNames:
      - qwen3-32b-fp8-vllm-agg-0-frontend
      readyReplicas: 8
      replicas: 8
      runtimeNamespace: qwen32-bench-qwen3-32b-fp8-vllm-agg
      updatedReplicas: 8
    VllmWorkerGpu05:
      componentKind: PodClique
      componentNames:
      - qwen3-32b-fp8-vllm-agg-0-vllmworkergpu05
      readyReplicas: 4
      replicas: 4
      runtimeNamespace: qwen32-bench-qwen3-32b-fp8-vllm-agg
      updatedReplicas: 4
    VllmWorkerGpu06:
      componentKind: PodClique
      componentNames:
      - qwen3-32b-fp8-vllm-agg-0-vllmworkergpu06
      readyReplicas: 4
      replicas: 4
      runtimeNamespace: qwen32-bench-qwen3-32b-fp8-vllm-agg
      updatedReplicas: 4
  conditions:
  - lastTransitionTime: "2026-08-12T12:37:56Z"
    message: All resources are ready
    reason: all_resources_are_ready
    status: "True"
    type: Ready
  observedGeneration: 1
  state: successful
